import { User, Role, Auction } from './types';

export const MOCK_USERS: User[] = [
  { id: 1, username: 'buyer1', role: Role.BUYER, password: 'password123' },
  { id: 2, username: 'seller1', role: Role.SELLER, password: 'password123' },
  { id: 3, username: 'admin', role: Role.ADMIN, password: '1234567890' },
  { id: 4, username: 'buyer2', role: Role.BUYER, password: 'password123' },
  { id: 5, username: 'seller2', role: Role.SELLER, password: 'password123' },
  { id: 6, username: 'mike_bids', role: Role.BUYER, password: 'password123' },
  { id: 7, username: 'jenna_sells', role: Role.SELLER, password: 'password123' },
];

const getRandomMinutes = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: 1,
    title: 'Vintage Leather Jacket',
    description: 'A classic 1980s leather jacket in excellent condition. Barely worn, with a timeless style.',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16e2d8?q=80&w=800&h=600&fit=crop',
    sellerId: 2,
    sellerName: 'seller1',
    startingPrice: 75,
    currentPrice: 75,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000), 
    bids: [],
    status: 'ACTIVE',
  },
  {
    id: 2,
    title: 'Antique Pocket Watch',
    description: 'A beautiful gold-plated pocket watch from the early 20th century. Still in working condition.',
    imageUrl: 'https://images.unsplash.com/photo-1589137323888-040d3a520261?q=80&w=800&h=600&fit=crop',
    sellerId: 5,
    sellerName: 'seller2',
    startingPrice: 200,
    currentPrice: 250,
    highestBidderId: 1,
    startTime: new Date(Date.now() - 12 * 60 * 60 * 1000), // Started 12 hours ago
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000), 
    bids: [{ id: 1, userId: 1, username: 'buyer1', amount: 250, timestamp: new Date(Date.now() - 60 * 1000) }],
    status: 'ACTIVE',
  },
  {
    id: 3,
    title: 'Signed First Edition Book',
    description: 'A rare, signed first edition of a popular fantasy novel. A must-have for collectors.',
    imageUrl: 'https://images.unsplash.com/photo-1618331835717-8017b219524d?q=80&w=800&h=600&fit=crop',
    sellerId: 2,
    sellerName: 'seller1',
    startingPrice: 150,
    currentPrice: 150,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [],
    status: 'ACTIVE',
  },
  {
    id: 5,
    title: "Classic 16-Bit Gaming Console",
    description: "Relive the glory days of gaming with this fully functional 16-bit console. Comes with two controllers and a classic adventure game.",
    imageUrl: 'https://images.unsplash.com/photo-1554832529-f1e17a44a694?q=80&w=800&h=600&fit=crop',
    sellerId: 2,
    sellerName: 'seller1',
    startingPrice: 120,
    currentPrice: 120,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [],
    status: 'ACTIVE',
  },
  {
    id: 6,
    title: "Abstract Canvas 'Metropolis'",
    description: "A vibrant, large-scale abstract painting on canvas. Perfect for a modern living room or office space. Signed by the artist.",
    imageUrl: 'https://images.unsplash.com/photo-1579541621910-2d6f73a3a228?q=80&w=800&h=600&fit=crop',
    sellerId: 5,
    sellerName: 'seller2',
    startingPrice: 350,
    currentPrice: 350,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [],
    status: 'ACTIVE',
  },
  {
    id: 7,
    title: "Pro DSLR Camera Body",
    description: "A professional-grade DSLR camera body, lightly used. Known for its crisp images and robust build. Lens not included.",
    imageUrl: 'https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?q=80&w=800&h=600&fit=crop',
    sellerId: 2,
    sellerName: 'seller1',
    startingPrice: 600,
    currentPrice: 650,
    highestBidderId: 4,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [{ id: 4, userId: 4, username: 'buyer2', amount: 650, timestamp: new Date(Date.now() - 2 * 60 * 1000) }],
    status: 'ACTIVE',
  },
  {
    id: 8,
    title: "Luxury Leather Handbag",
    description: "An iconic designer handbag in pristine condition. Made from genuine Italian leather, comes with original dust bag.",
    imageUrl: 'https://images.unsplash.com/photo-1590737039649-65d13a69b74b?q=80&w=800&h=600&fit=crop',
    sellerId: 5,
    sellerName: 'seller2',
    startingPrice: 500,
    currentPrice: 500,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [],
    status: 'ACTIVE',
  },
  {
    id: 9,
    title: "Limited Edition Vinyl LP",
    description: "A rare, limited press vinyl record from a legendary rock band. The sleeve is in mint condition.",
    imageUrl: 'https://images.unsplash.com/photo-1549490105-03701217e6e3?q=80&w=800&h=600&fit=crop',
    sellerId: 2,
    sellerName: 'seller1',
    startingPrice: 90,
    currentPrice: 110,
    highestBidderId: 1,
    startTime: new Date(),
    endTime: new Date(Date.now() + getRandomMinutes(5, 45) * 60 * 1000),
    bids: [{ id: 5, userId: 1, username: 'buyer1', amount: 110, timestamp: new Date(Date.now() - 5 * 60 * 1000) }],
    status: 'ACTIVE',
  },
  {
    id: 4,
    title: 'Mid-Century Modern Armchair',
    description: 'An iconic armchair design from the 1960s. Restored with original materials.',
    imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=800&h=600&fit=crop',
    sellerId: 5,
    sellerName: 'seller2',
    startingPrice: 400,
    currentPrice: 550,
    highestBidderId: 4,
    startTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Started 2 days ago
    endTime: new Date(Date.now() - 1 * 60 * 1000), // Ended 1 minute ago
    bids: [
        { id: 2, userId: 1, username: 'buyer1', amount: 450, timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000) },
        { id: 3, userId: 4, username: 'buyer2', amount: 550, timestamp: new Date(Date.now() - 2 * 60 * 1000) }
    ],
    status: 'ENDED',
  },
];